### ISSUE TITLE
When using the --multiple flag there's no ending condition

### ISSUE THREAD

**Issue by Giuliano1993** [Giuliano1993/make-js-component#100]
### Reproduction steps

```bash
It's cool we can now create many components thank to our multiple approach.
Still when using the --multiple flag it will still continue asking for creating other components unless we stop the process with ctrl-c.
It would be nice to add an exit condition, so if --multiple is flagged, then when the user must write the component name, if they type "exit" then the application gracefully stops
```

### Do you want to work on this issue?

No

**Comment by mjs001** [comment]
Hello, I really like this project. May I be assigned to this issue? I am wanting to get into contributing to projects I really like. Thank you!

**Comment by Giuliano1993** [comment]
Hello @mjs001 I'm really glad you like the project! Of course you can have this assigned , thank you for willing to contribute!

**Comment by mjs001** [comment]
Of course, thank you. I will get started on this.
