### ISSUE TITLE
Add control for empty component name

### ISSUE THREAD

**Issue by Giuliano1993** [Giuliano1993/make-js-component#16]
### Reproduction steps

```bash
When starting the process, it now allows to go on after empty component name. That should be avoided
```

### Do you want to work on this issue?

No

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by Giuliano1993** [comment]
Hey @IrfanSalim ! Thank you for being willing to work on this! I assigned this to you 😄
