### ISSUE TITLE
Implement Commander to skip component name step

### ISSUE THREAD

**Issue by Giuliano1993** [Giuliano1993/make-js-component#21]
That would be cool, instead of going necessarily trough all the wizard, to be able to give an optional argument after the `npx make-js-component` in order to skip the component name writing step and go right into the next options

the command would then look like
`npx make-js-command --name=[componentName]`

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by Giuliano1993** [comment]
Okay @IrfanSalim assigning this to you, thank you 😄
