### ISSUE TITLE
[react] Add the style option 

### ISSUE THREAD

**Issue by giuppidev** [Giuliano1993/make-js-component#24]
It would be nice to have some styling option on React component creation, for example:

- Tailwind (just adding some basic classes)
- Styled component
- Modules (the more difficult one because it involves another file creation)

**Comment by Giuliano1993** [comment]
That is a nice idea! I'm just closing this and splitting it into two separate issue, one for the one only related to one file (tailwind and styled ) and another for the modules one! Thanks for raising!
