### ISSUE TITLE
[ react ] add module style option

### ISSUE THREAD

**Issue by Giuliano1993** [Giuliano1993/make-js-component#26]
It would be nice to have, as a styling option for react, the possibility use modules styling

**Comment by Giuliano1993** [comment]
Hi @fmineo ! You're welcome to take on this issue! Yes I think this can be a good approach! When the wizard ends you should not only copy the  template but also the module!
Not an expert about React, but does the module for styling goes in the same folder of the component, in that case?

**Comment by fmineo** [comment]
Hi @Giuliano1993, usually a css module can be found in any folder. However, for simplicity I would say to create the css module in the same folder as the component.
