### ISSUE TITLE
Add types on wizard.mts

### ISSUE THREAD

**Issue by giuseppevignanello** [Giuliano1993/make-js-component#32]
### Reproduction steps

The input in wizard.mts have no type and could have `string`. 

Also the whole `const wizard` could have a type return like `Promise<Answers>`
```


### Do you want to work on this issue?

Yes

**Comment by Giuliano1993** [comment]
Hi @giuseppevignanello I'm seeing you're wishing to work also on this issue, but you've already got another assigned! For the moment I prefer to assign one issue at a time to people in order to allow more people to participate! But thank you so much for rising the issue!

**Comment by giuseppevignanello** [comment]
It's seems fair 👍

**Comment by giuseppesciacca** [comment]
Hey guys! Can I take this?

**Comment by Giuliano1993** [comment]
Yes @giuseppesciacca of course! :D Assigning this to you!
