### ISSUE TITLE
Add another component question

### ISSUE THREAD

**Issue by Giuliano1993** [Giuliano1993/make-js-component#50]
When the component creation is complete, ask the user if they want to create another component.
This would allow to directly run again the command and create more component at once

**Comment by Giuliano1993** [comment]
Hi @cristinagenduso ! You're right, the two issues go together for the reasons you mentioned.
As you said #56 is momentarily stalled; I asked the dev to whom it was assigned if he's still interested in solving it; if I get no answer in some days I'd be happy to assign both issues to you 😄 I will assign you this, for starting, but if you want you can wait to know about the #56  so you can work on them together or work after the relative PR, is it okay for you?

**Comment by cristinagenduso** [comment]
Sounds perfect to me! I’ll start working on this and as soon as you have news for #56 let me know.

**Comment by Giuliano1993** [comment]
This is fine! The other dev gave up on #56 so if you add a comment over there too to have it assigned I can assign you both at this point 😄
