### ISSUE TITLE
Add --multiple flag

### ISSUE THREAD

**Issue by Giuliano1993** [Giuliano1993/make-js-component#56]
We could add a --multiple flag that, if checked, at the end of each component creation asks the user if he wants to exit.
Otherwise the creator command will be launched once again.

Doing the user is able to easily create more components in a row

**Comment by andrearanica** [comment]
Hi Giuliano, if you want now I'm free ✌🏻

**Comment by Giuliano1993** [comment]
Ahaha Fine! You take it from here 😃

**Comment by Giuliano1993** [comment]
Hi @andrearanica are you still interested in working on this issue? Otherwise, I'd leave it for others interested in it and you can take on a new one when you feel to 😄

**Comment by andrearanica** [comment]
Yes I was trying to do this issue but I was blocked because I don't know how to continue, if there is someone who wants to do it assign it to him

**Comment by Giuliano1993** [comment]
Okay then :) Thank you for the quick response, I'm reassigning this then :)

**Comment by cristinagenduso** [comment]
Hi @Giuliano1993! I would like to work on this issue.

**Comment by Giuliano1993** [comment]
Perfect @cristinagenduso I'm assigning this to you then! Thanks!
