### ISSUE TITLE
[ vue ] Add possibility to create the component for a Nuxt App instead of a Vue app

### ISSUE THREAD

**Issue by Giuliano1993** [Giuliano1993/make-js-component#61]
Nuxt framework uses Vue as its frontend. 
The components won't change from a normal vue app, but the components shall be created into the `./components` folder instead of the `./src/components` folder.
Add a question to the Vue installer to ask if the user is working in a vue app or in a nuxt one

**Comment by giuseppesciacca** [comment]
Can I work on this issue?

**Comment by Giuliano1993** [comment]
Of course! Thank you 😄
