### ISSUE TITLE
Documentation for working with flags

### ISSUE THREAD

**Issue by Giuliano1993** [Giuliano1993/make-js-component#66]
We need a comprehensive an cohese documentation about working directly with flags.
At the moment we have 3 flags
`--name <name>` allows to specify the component name
`-f <framework>` let you specify one of the available frameworks ( at the moment of writing Vue, React, Angular, Qwik, Svelte and Astro)  
`--folder <path>` the components subfolder in which add the component. The folder is created if it doesn't exsists

**Comment by mjs001** [comment]
I'd be happy to work on this ticket. I believe the only flag not mentioned right now is the "--multiple" flag. I could add that and rewrite the documentation a little bit for clarity if desired.

**Comment by Giuliano1993** [comment]
That would be great yes!
When the issue was first opened the --multiple option didn't exist yet, so if you're willing to add it and give some more organic organization to this part of the documentation that would be great :D

**Comment by Giuliano1993** [comment]
If you have any doubt don't hesitate to contact me so we can wor that out!

**Comment by mjs001** [comment]
Thank you, I will definitely reach out when needed. Happy to help.
