### ISSUE TITLE
Define defaults for React

### ISSUE THREAD

**Issue by Giuliano1993** [Giuliano1993/make-js-component#69]
We might need some default set for each framework, in order to skip the post framework selections step with a flag.

This issue is about picking the defaults for React

**Comment by giuseppesciacca** [comment]
Could I take this issue?

**Comment by Giuliano1993** [comment]
Of course! @giuseppesciacca  Thank you 😄

**Comment by giuseppesciacca** [comment]
PR: https://github.com/Giuliano1993/make-js-component/pull/90
