### ISSUE TITLE
Define defaults for Svelte

### ISSUE THREAD

**Issue by Giuliano1993** [Giuliano1993/make-js-component#70]
We might need some default set for each framework, in order to skip the post framework selections step with a flag.

This issue is about picking the defaults for Svelte

**Comment by Giuliano1993** [comment]
Hi @cristinagenduso ! Of course go ahead, thank you so much :) 
Start with this one and after it gets merged you can move to #71 !
Thank you as always for willing to contribute!

**Comment by cristinagenduso** [comment]
It seems like Svelte only has one prompt (Typescript) for now, and it is already set to True by default. So I think this issue can be closed without any changes needed.

**Comment by Giuliano1993** [comment]
Yes @cristinagenduso  you're right, this makes sense to me, thanks for noticing!
