### ISSUE TITLE
Prevent old components from being overwritten by creating homonymous components

### ISSUE THREAD

**Issue by cristinagenduso** [Giuliano1993/make-js-component#74]
Currently, when a new component is created in the same directory and with the same name (and extension clearly) as one that already exists, the latter is overwritten without any kind of warning.
I think it would be useful to introduce a warning if you are trying to overwrite an already existing component and ask for confirmation whether or not you intend to proceed.

**Comment by cristinagenduso** [comment]
Thanks for the opportunity, yes I would love to work on this. I wanted to leave room for others, but since I closed my issue, I'd like to dedicate myself to this one!

**Comment by Giuliano1993** [comment]
Yes thank you I really appreciate the spirit 🙏 but since you closed your issue and there are also a bunch of new ones there's no prob for you to take this! Thank you really much! 😄
